-- Masquerade V7 initial schema
create extension if not exists pgcrypto;

create table if not exists profiles(
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  display_name text,
  avatar_url text,
  preferred_difficulty text default 'devious',
  created_at timestamptz default now()
);

create table if not exists puzzles_private(
  id uuid primary key default gen_random_uuid(),
  clue_type text not null,
  clue_text text not null,
  answer text not null,
  accepted_answers text[] default '{}',
  numeric_answer boolean default false,
  difficulty_score int default 50 check(difficulty_score between 1 and 100),
  difficulty_band text not null check(difficulty_band in ('clever','devious','fiendish')),
  hint_1 text not null,
  hint_2 text not null,
  hint_3 text not null,
  explanation text,
  is_final_mask boolean default false,
  status text default 'draft' check(status in ('draft','testing','approved','scheduled','published','retired')),
  created_at timestamptz default now()
);

create view puzzles_public as
select id,clue_type,clue_text,difficulty_score,difficulty_band,is_final_mask,status,created_at
from puzzles_private;

create table if not exists daily_games(
  id uuid primary key default gen_random_uuid(),
  game_date date not null,
  game_number bigint generated by default as identity,
  difficulty_band text not null,
  published boolean default false,
  created_at timestamptz default now(),
  unique(game_date,difficulty_band)
);

create table if not exists daily_game_puzzles(
  daily_game_id uuid references daily_games(id) on delete cascade,
  puzzle_id uuid references puzzles_private(id),
  position int not null check(position between 1 and 5),
  primary key(daily_game_id,position)
);

create table if not exists game_sessions(
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  daily_game_id uuid references daily_games(id),
  difficulty_band text not null,
  status text default 'active' check(status in ('active','completed','quit')),
  current_position int default 1,
  started_at timestamptz default now(),
  completed_at timestamptz,
  score int default 0,
  hints_used int default 0,
  pure_solves int default 0,
  solve_time_ms bigint default 0,
  unique(user_id,daily_game_id)
);

create table if not exists puzzle_results(
  id uuid primary key default gen_random_uuid(),
  session_id uuid references game_sessions(id) on delete cascade,
  puzzle_id uuid references puzzles_private(id),
  attempts int default 0,
  hints_used int default 0,
  solved boolean default false,
  score int default 0,
  pure_solve boolean default false,
  first_try boolean default false,
  solved_at timestamptz,
  unique(session_id,puzzle_id)
);

create table if not exists puzzle_attempts(
  id uuid primary key default gen_random_uuid(),
  session_id uuid references game_sessions(id) on delete cascade,
  puzzle_id uuid references puzzles_private(id),
  attempt_number int not null,
  submitted_answer text not null,
  is_correct boolean default false,
  created_at timestamptz default now()
);

create table if not exists challenges(
  id uuid primary key default gen_random_uuid(),
  challenger_id uuid references auth.users(id) on delete cascade,
  challenged_id uuid references auth.users(id) on delete set null,
  challenged_email text,
  daily_game_id uuid references daily_games(id),
  invite_code text unique not null,
  status text default 'pending' check(status in ('pending','accepted','completed','expired')),
  created_at timestamptz default now()
);

create table if not exists crews(
  id uuid primary key default gen_random_uuid(),
  name text not null,
  owner_id uuid references auth.users(id) on delete cascade,
  invite_code text unique not null,
  created_at timestamptz default now()
);

create table if not exists crew_members(
  crew_id uuid references crews(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  joined_at timestamptz default now(),
  primary key(crew_id,user_id)
);

alter table profiles enable row level security;
alter table daily_games enable row level security;
alter table daily_game_puzzles enable row level security;
alter table game_sessions enable row level security;
alter table puzzle_results enable row level security;
alter table puzzle_attempts enable row level security;
alter table challenges enable row level security;
alter table crews enable row level security;
alter table crew_members enable row level security;
alter table puzzles_private enable row level security;

create policy "users read own profile" on profiles for select using(auth.uid()=id);
create policy "users update own profile" on profiles for update using(auth.uid()=id);
create policy "published daily games readable" on daily_games for select using(published=true);
create policy "daily game puzzle links readable" on daily_game_puzzles for select using(true);
create policy "own sessions" on game_sessions for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own results" on puzzle_results for select using(exists(select 1 from game_sessions s where s.id=session_id and s.user_id=auth.uid()));
create policy "own attempts" on puzzle_attempts for select using(exists(select 1 from game_sessions s where s.id=session_id and s.user_id=auth.uid()));
create policy "challenge participants read" on challenges for select using(auth.uid()=challenger_id or auth.uid()=challenged_id);
create policy "challenge creator inserts" on challenges for insert with check(auth.uid()=challenger_id);
create policy "crew members read crews" on crews for select using(exists(select 1 from crew_members cm where cm.crew_id=id and cm.user_id=auth.uid()) or owner_id=auth.uid());
create policy "crew owner creates" on crews for insert with check(auth.uid()=owner_id);
create policy "members read membership" on crew_members for select using(user_id=auth.uid() or exists(select 1 from crews c where c.id=crew_id and c.owner_id=auth.uid()));
create policy "self join membership" on crew_members for insert with check(user_id=auth.uid());

-- IMPORTANT:
-- puzzles_private deliberately has no general SELECT policy. Answer/hint access should occur
-- from server-side trusted routes using a service-role client in production.
