create extension if not exists pgcrypto;

create table if not exists users(
  id uuid primary key default gen_random_uuid(),
  entra_object_id text unique not null,
  email text unique not null,
  username text unique,
  display_name text,
  avatar_url text,
  preferred_difficulty text default 'devious',
  created_at timestamptz default now()
);

create table if not exists puzzles(
  id uuid primary key default gen_random_uuid(),
  clue_type text not null,
  clue_text text not null,
  answer text not null,
  accepted_answers text[] default '{}',
  numeric_answer boolean default false,
  difficulty_score int default 50 check(difficulty_score between 1 and 100),
  difficulty_band text not null check(difficulty_band in ('clever','devious','fiendish')),
  hint_1 text not null,
  hint_2 text not null,
  hint_3 text not null,
  explanation text,
  is_final_mask boolean default false,
  status text default 'draft' check(status in ('draft','testing','approved','scheduled','published','retired')),
  created_at timestamptz default now()
);

create table if not exists daily_games(
  id uuid primary key default gen_random_uuid(),
  game_date date not null,
  game_number bigint generated by default as identity,
  difficulty_band text not null check(difficulty_band in ('clever','devious','fiendish')),
  published boolean default false,
  created_at timestamptz default now(),
  unique(game_date,difficulty_band)
);
create table if not exists daily_game_puzzles(
  daily_game_id uuid references daily_games(id) on delete cascade,
  puzzle_id uuid references puzzles(id),
  position int not null check(position between 1 and 5),
  primary key(daily_game_id,position)
);
create table if not exists game_sessions(
  id uuid primary key default gen_random_uuid(),
  user_id uuid references users(id) on delete cascade,
  daily_game_id uuid references daily_games(id),
  difficulty_band text not null,
  status text default 'active' check(status in ('active','completed','quit')),
  current_position int default 1,
  started_at timestamptz default now(), completed_at timestamptz,
  score int default 0,hints_used int default 0,pure_solves int default 0,solve_time_ms bigint default 0,
  unique(user_id,daily_game_id)
);
create unique index if not exists one_active_session_per_user on game_sessions(user_id) where status='active';
create table if not exists puzzle_results(
  id uuid primary key default gen_random_uuid(),session_id uuid references game_sessions(id) on delete cascade,puzzle_id uuid references puzzles(id),
  attempts int default 0,hints_used int default 0,solved boolean default false,score int default 0,pure_solve boolean default false,first_try boolean default false,solved_at timestamptz,
  unique(session_id,puzzle_id)
);
create table if not exists puzzle_attempts(
  id uuid primary key default gen_random_uuid(),session_id uuid references game_sessions(id) on delete cascade,puzzle_id uuid references puzzles(id),attempt_number int not null,submitted_answer text not null,is_correct boolean default false,created_at timestamptz default now()
);
create table if not exists challenges(
  id uuid primary key default gen_random_uuid(),challenger_id uuid references users(id) on delete cascade,challenged_id uuid references users(id) on delete set null,challenged_email text,daily_game_id uuid references daily_games(id),invite_code text unique not null,status text default 'pending' check(status in ('pending','accepted','completed','expired')),created_at timestamptz default now()
);
create table if not exists crews(
  id uuid primary key default gen_random_uuid(),name text not null,owner_id uuid references users(id) on delete cascade,invite_code text unique not null,created_at timestamptz default now()
);
create table if not exists crew_members(
  crew_id uuid references crews(id) on delete cascade,user_id uuid references users(id) on delete cascade,joined_at timestamptz default now(),primary key(crew_id,user_id)
);
